# 아이템 7 결과 부족이 발생할 경우 null과 Failure를 사용하라

- 함수가 원하는 결과를 만들어 낼 수 없을 때가 있다.
    - ex) api 요청 시 네트워크 문제가 있는 경우
    - ex) 텍스트를 파싱하려는데 텍스트 형식이 맞지 않는 경우
- 이러한 상황을 처리하는 메커니즘은 다음 두 가지가 있다.
    - `null` 또는 ‘실패를 나타내는 `sealed` 클래스를 리턴
    - 예외를 `throw`
- 일단 예외는 정보를 전달하는 방법으로 사용해서는 안 된다.
    - 예외는 잘못된 특정한 상황을 나타내야 한다.
    - 예외적인 상황이 발생했을 때만 사용해야 한다.
- 충분히 예측할 수 있는 범위의 오류는 `null`과 `Failure`를, 예측하기 어려운 오류는 `throw`로 처리하는 것이 좋다.
- `null`과 `Failure`는 예상되는 오류를 표현할 때 좋은 방안이다.
    - 추가적인 정보를 전달해야 한다면 `sealed` `result`를, 그렇지 않다면 null을 사용하는 것이 일반적이다.
    - 이런 오류는 다루기 쉬우며 놓치기 어렵다.
    - `null`과 `Failure`을 다루려면 코틀린에선 컴파일 단계에서부터 명시적으로 다뤄야하기 때문이다.

```kotlin
inline fun <reified T> String.readObjectOrNull(): T? {
	// ...
	if (incorrectSign) {
		return null
	}
	// ...
	return result
}

inline fun <reified T> String.readObject(): Result<T> {
	// ...
	if (incorrectSign) {
		return Failure(JsonParsingException())
	}
	// ...
	return Success(result)
}
```

- `List`에선 요소를 추출할 때 일반적으로 아래 두 가지 형태의 함수를 사용한다.
    - `get` - 만약 요소가 해당 위치에 없다면 `IndexOutOfBoundsException`을 발생
    - `getOrNull` - out of range 오류 대신 `null`을 리턴
    - 런타임 예외를 피하기 위해 `getOrNull`과 Elvis 연산자를 사용하는 것이 좋다.
