# Lec 07. 코틀린에서 예외를 다루는 방법

## 1. try catch finally 구문

- 코틀린에서 `try-catch` 자체는 자바와 유사하다.
- 문자열을 받아 `Int`로 형변환하는 예제

```kotlin
fun parseIntOrThrow(str: String): Int {
  try {
    return str.toInt()
  } catch (e: NumberFormatException) { // 예외 시 예외 발생
    throw IllegalArgumentException("숫자가 아닙니다.")
  }
}
```

- 코틀린에서 `try-catch` 자체가 Expression이기 대문에 바로 `return`할 수도 있다.

```kotlin
fun parseIntOrThrow(str: String): Int? {
  return try {
    str.toInt()
  } catch (e: NumberFormatException) { // 예외 시 null 반환
    null
  }
}
```

## 2. Checked Exception과 Unchecked Exception

- 자바에선 `IOException` 등은 Checked Exception이기 때문에 `throw` 하는 등의 처리가 필요하다.
- 하지만 코틀린에선 Checked Exception과 Unchecked Exception을 구분하지 않고 모두 Unchecked Exception이다.

## 3. try with resources

- 코틀린에선 `try-with-resources` 구문이 없다.
- 파일을 읽어 출력하는 예제

```java
// 자바
public void readFile(String path) throws IOException {
  try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
    System.out.println(reader.readLine());
  }
}
```

```kotlin
// 코틀린
fun readFile(path: String?) {
    BufferedReader(FileReader(path)).use { reader -> 
        println(reader.readLine()) 
    }
}
```

- 코틀린에선 `BufferedReader`의 확장함수 `use`를 활용하여 작성할 수 있다.
- 코틀린의 언어적 특징을 활용해 `close`를 호출해준다.
